---
title: "Untitled"
author: "Tom Swan"
date: "07/05/2021"
output: html_document
---

Loading packages
```{r}
library(qtl)
library(ggplot2)
library(pscl)
library(boot)
library(psych) 
library(stats) 
library(MASS)
library(car)
library(lmtest)
library(lme4)
library(tidyverse)
library(tibble)
library(aods3)
library(emmeans)
library(dplyr)
library(MuMIn)
library(DHARMa)
library(blmeco)
library(cowplot)
library(ResourceSelection)
library(ggrepel)
library(arm)
```

Importing data
```{r}
albo_1SD_data <- read.csv("TSI_data_albo_cutoff.csv")
```

Running models
```{r}
SD1_iteraction_albo <- glmer(sugar ~ time*sex+habitat + (1|day) + (1|station), family = binomial, data = albo_1SD_data)
summary(SD1_iteraction_albo)
Anova(SD1_iteraction_albo)

hoslem.test(albo_1SD_data$sugar, fitted(SD1_iteraction_albo))

#either way with 1 SD, the effect of habitat on its own is still highly insignificant. But when combinded with the other factors becomes highly significant. 

```

What if you group them by male and female 1 SD. Does this change the result from the male and female 3 SD?
```{r}
albo_female_1SD <- read.csv("TSI_data_albo_cutoff_female_1SD.csv")

albo_male_1SD <- read.csv("TSI_data_albo_cutoff_male_1SD.csv")
```

Running models females
```{r}

albo_female_1SD_glm <- glmer(sugar ~ time+habitat + (1|day) + (1|station), family = binomial, data = albo_female_1SD)
summary(SD1_iteraction_albo)
Anova(albo_female_1SD_glm)

hoslem.test(albo_1SD_data$sugar, fitted(SD1_iteraction_albo))


#1 SD for the females - habitat is more significant, than when testing with 3 SD. Everything else is the same though.
#also the simpsons paradox occurs with the females when only habitat is run. 
#the hoslem GOF test is not significant though (sig for 3 SD)
```
Running models males
```{r}
albo_male_1SD_glm_new <- glmer(sugar ~ time+habitat + (1|day) + (1|station), family = binomial, data = albo_male_1SD)
Anova(albo_male_1SD_glm_new)

hoslem.test(albo_male_1SD$sugar, fitted(albo_male_1SD_glm_new))

#time is highly significant - the same as the 3SD model.
#however the H-L GOF test is significant. 
#I think at the end of the day it comes down to proportion sugarfed. 
```

